In [1]:
import pandas as pd

In [26]:
df_res = pd.read_csv('survey_results_public.csv')
df_res

/var/folders/fr/0xscpcvn2lq1f2m6wscjbyqw0000gn/T/ipykernel_9646/2197616300.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df_res = pd.read_csv('survey_results_public.csv')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

In [3]:
df_sch = pd.read_csv('survey_results_schema.csv')
df_sch

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [4]:
pd.set_option('display.max_columns', None)

Завдання 1. Підрахунок загальної кількості респондентів

In [44]:
df_resp = df['ResponseId'].nunique()
df_resp

#загальна кількість респондентів складає 49191 опитаних

49191

Завдання 2. Аналіз повноти відповідей респондентів

In [164]:
sch_quest = set(df_sch['qname'].unique())
sch_quest

len(sch_quest)

#кількість запитань до респондентів складає 139

139

In [38]:
res_columns = set(df_res.columns)
res_columns

len(res_columns)

#загальна кількість стовпців складає 172

172

In [36]:
common_columns = list(sch_quest.intersection(res_columns))
common_columns

len(common_columns)

#перелік запитань, які є в обох таблицях, складає 126

126

In [39]:
df_common = df_res[common_columns]
df_common

,JobSatPoints_3,TechEndorse_1,SOTagsWant Entry,DatabaseChoice,SOVisitFreq,NewRole,OfficeStackWantEntry,SO_Dev_Content,SODuration,EmploymentAddl,SO_Actions_10,TechOppose_5,AIAgentChange,JobSat,JobSatPoints_9,AIAcc,TechOppose_15,AIAgentKnowWrite,TechEndorse_2,PlatformWantEntry,CommPlatformHaveEntr,JobSatPoints_14,WebframeHaveEntry,TechEndorse_3,AIThreat,TechOppose_7,JobSatPoints_10,AIAgent_Uses,PurchaseInfluence,AIModelsWantEntry,SOFriction,TechOppose_11,TechEndorse_13_TEXT,SOAccount,CommPlatformWantEntr,SO_Actions_15,TechOppose_13,LearnCodeChoose,JobSatPoints_4,ICorPM,OfficeStackHaveEntry,AIExplain,AIAgentOrchestration,TechEndorse_5,TechOppose_3,SO_Actions_15_TEXT,SO_Actions_6,AgentUsesGeneral,PlatformChoice,AIAgentOrchWrite,AIFrustration,AIComplex,AIAgentKnowledge,TechOppose_1,SOPartFreq,JobSatPoints_5,JobSatPoints_13,TechOppose_15_TEXT,WebframeChoice,TechEndorse_6,SO_Actions_1,TechOppose_2,JobSatPoints_6,TechEndorse_4,DatabaseHaveEntry,TechEndorse_8,YearsCode,Currency,SO_Actions_3,ToolCountPersonal,TechOppose_16,LanguagesHaveEntry,JobSatPoints_16,AIModelsChoice,JobSatPoints_11,EdLevel,RemoteWork,AIModelsHaveEntry,SO_Actions_7,AISent,AIAgentObserveSecure,SO_Actions_4,LanguageChoice,TechEndorseIntro,SO_Actions_9,SO_Actions_16,WorkExp,DevEnvWantEntry,PlatformHaveEntry,DevEnvHaveEntry,SO_Actions_5,JobSatPoints_2,ToolCountWork,AIAgentExtWrite,CompTotal,JobSatPoints_7,TechOppose_9,DevEnvsChoice,AIAgentObsWrite,AISelect,Age,JobSatPoints_15_TEXT,SOComm,JobSatPoints_8,LanguagesWantEntry,TechEndorse_7,DevType,JobSatPoints_15,LearnCodeAI,AIOpen,TechEndorse_13,JobSatPoints_1,Employment,AIAgents,TechEndorse_9,OrgSize,LearnCode,SOTagsHaveEntry,AILearnHow,AIHuman,DatabaseWantEntry,WebframeWantEntry,Industry,Country,AIAgentExternal,MainBranch
0,4.0,10.0,NaN,Yes,A few times per week,I have neither consider or transitioned into a...,NaN,NaN,Between 5 and 10 years,"Caring for dependents (children, elderly, etc.)",11.0,12.0,Not at all or minimally,10.0,2.0,Neither trust nor distrust,16.0,NaN,7.0,NaN,NaN,14.0,NaN,9.0,I'm not sure,11.0,6.0,Software engineering,"Yes, I influenced the purchase of a substantia...",NaN,"Rarely, almost never",6.0,NaN,Yes,NaN,15.0,13.0,"Yes, I am not new to coding but am learning ne...",9.0,People manager,NaN,No,Vertex AI,3.0,8.0,NaN,7.0,NaN,Yes,NaN,"AI solutions that are almost right, but not quite",Bad at handling complex tasks,NaN,15.0,I have never participated in Q&A on Stack Over...,5.0,13.0,NaN,No,11.0,1.0,7.0,10.0,6.0,NaN,1.0,14.0,EUR European Euro,6.0,3.0,3.0,NaN,8.0,Yes,7.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Remote,NaN,9.0,Indifferent,NaN,2.0,Yes,Work,8.0,NaN,8.0,NaN,NaN,NaN,3.0,1.0,7.0,NaN,52800.0,12.0,1.0,Yes,NaN,"Yes, I use AI tools monthly or infrequently",25-34 years old,NaN,Neutral,11.0,NaN,12.0,"Developer, mobile",15.0,"Yes, I learned how to use AI-enabled tools for...","Troubleshooting, profiling, debugging",14.0,3.0,Employed,"Yes, I use AI agents at work monthly or infreq...",8.0,20 to 99 employees,Online Courses or Certification (includes all ...,NaN,AI CodeGen tools or AI-enabled apps,When I don’t trust AI’s answers,NaN,NaN,Fintech,Ukraine,ChatGPT,I am a developer by profession
1,3.0,13.0,NaN,Yes,Multiple times per day,I have transitioned into a new career and/or i...,NaN,Chat (people);Message Boards;Long-form article...,Between 10 and 15 years,NaN,11.0,10.0,Not at all or minimally,9.0,11.0,Neither trust nor distrust,15.0,NaN,1.0,NaN,NaN,14.0,NaN,2.0,I'm not sure,9.0,4.0,NaN,No,NaN,About half of the time,4.0,NaN,Not sure/can't remember,NaN,15.0,2.0,"Yes, I am not new to coding but am learning ne...",9.0,Individual contributor,NaN,No,NaN,4.0,13.0,NaN,4.0,NaN,Yes,NaN,"AI solutions that are almost right, but not qu...",Bad at handling complex tasks,NaN,14.0,"Infrequently, less than once per year",12.0,13.0,NaN,Yes,3.0,6.0,1.0,1.0,9.0,NaN,5.0,10.0,EUR European Euro,5.0,5.0,5.0,NaN,5.0,Yes,7.0,"Associate degree (A.A., A.S., etc.)","Hybrid (some in-person, leans heavy to flexibi...",NaN,10.0,Indifferent,NaN,8.0,Yes,Personal Project,9.0,NaN,2.0,NaN,NaN,NaN,2.0,8.0,6.0,NaN,90000.0,6.0,3.0,Yes,NaN,"Yes, I use AI tools weekly",25-34 years old,NaN,"Yes, somewhat",2.0,NaN,12.0,"Developer, back-end",15.0,"Yes, I learned how to use AI-enabled tools for...",All skills. AI is a flop.,14.0,10.0,Employed,"No, and I don't plan to",7.0,500 to 999 employees,Online Courses or Certification (includes all ...,NaN,AI CodeGen tools or AI-enabled apps,When I don’t trust AI’s answers;When I want to...,NaN,NaN,Retail and Consumer Services,Netherlands,NaN,I am a developer by profession
2,7.0,12.0,NaN,Yes,A few times per week,I have transitioned into a new career and/or i...,NaN,Chat (people);Videos;Lists of recommendations ...,Between 5 and 10 years,None of the above,11.0,12.0,"Yes, somewhat",8.0,2.0,Somewhat trust,15.0,NaN,2.0,NaN,NaN,14.0,NaN,3.0,No,13.0,4.0,Software engineering,No,NaN,About half of the time,9.0,NaN,Not sure/can't remember,NaN,15.0,4.0,"Yes, I am not new to coding but am learning ne...",11.0,NaN,NaN,No,NaN,5.0,2.0,NaN,2.0,Multi-platform search enablement,Yes,NaN,"AI solutions that are almost right, but not qu...",Neither good or bad at handling complex tasks,Redis,8.0,"Infrequently, less than once per year",8.0,13.0,NaN,Yes,10.0,3.0,1.0,12.0,7.0,NaN,1.0,12.0,UAH Ukrainian hryvnia,4.0,3.0,11.0,NaN,10.0,Yes,3.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,9.0,Favorable,NaN,5.0,Yes,Work,7.0,NaN,10.0,NaN,NaN,NaN,1.0,6.0,3.0,NaN,2214000.0,1.0,3.0,Yes,NaN,"Yes, I use AI tools daily",35-44 years old,NaN,Neutral,5.0,NaN,13.0,"Developer, front-end",15.0,"Yes, I learned how to use AI-enabled tools for...","Understand how things actually work, problem s...",14.0,9.0,"Independent contractor, freelancer, or self-em...","Yes, I use AI agents at work weekly",4.0,NaN,Online Courses or Certification (includes all ...,NaN,AI CodeGen tools or AI-enabled apps;Technical ...,When I don’t trust AI’s answers;When I want to...,NaN,Solid.js,Software Development,Ukraine,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,I am a developer by profession
3,4.0,2.0,NaN,No,A few times per month or weekly,I have neither consider or transitioned into a...,NaN,Videos;Chat (bot/AI),Between 3 and 5 years,None of the above,11.0,4.0,Not at all or minimally,6.0,10.0,Somewhat trust,15.0,NaN,12.0,NaN,NaN,14.0,NaN,6.0,No,13.0,11.0,Software engineering,No,NaN,"Rarely, almost never",2.0,NaN,Yes,NaN,15.0,7.0,"Yes, I am not new to coding but am learning ne...",5.0,Individual contributor,NaN,NO,NaN,13.0,8.0,NaN,7.0,Language processing,Yes,NaN,"AI solutions that are almost right, but not qu...",Bad at handling complex tasks,NaN,10.0,I have never participated in Q&A on Stack Over...,6.0,13.0,NaN,Yes,3.0,1.0,5.0,7.0,5.0,NaN,11.0,5.0,EUR European Euro,4.0,NaN,1.0,NaN,3.0,No,12.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Remote,NaN,9.0,Favorable,NaN,5.0,Yes,Personal Project,8.0,NaN,4.0,NaN,NaN,NaN,6.0,2.0,NaN,NaN,31200.0,8.0,12.0,No,NaN,"Yes, I use AI tools weekly",35-44 years old,NaN,Neutral,9.0,NaN,8.0,"Developer, back-end",15.0,"Yes, I learned how to use AI-enabled tools for...",NaN,14.0,1.0,Employed,"Yes, I use AI agents at work monthly or infreq...",7.0,"10,000 or more employees","Other online resources (e.g. standard search, ...",NaN,AI CodeGen tools or AI-enabled apps;Videos (no...,When I don’t trust AI’s answers;When I want to...,NaN,NaN,Retail and Consumer Services,Ukraine,ChatGPT;Claude Code,I am a developer by profession
4,11.0,6.0,NaN,Yes,A few times per month or weekly,I have neither consider or transitioned into a...,NaN,Long-form articles,Between 5 and 10 years,"Caring for dependents (children, elderly, etc.)",12.0,9.0,"Yes, to a great extent",7.0,7.0,Neither trust nor distrust,15.0,NaN,3.0,NaN,NaN,10.0,NaN,1.0,No,12.0,2.0,NaN,"Yes, I endorsed a tool that was open-source an...",NaN,"Rarely, almost never",1.0,NaN,No,NaN,15.0,8.0,"No, I am not new to coding and did not learn n...",13.0,NaN,NaN,partly,NaN,10.0,3.0,NaN,5.0,NaN,Yes,NaN,"AI solutions that are almost right, but not quite","Good, but not great at handling complex tasks",NaN,7.0,"Infrequently, less than once per year",14.0,12.0,NaN,Yes,8.0,1.0,13.0,8.0,9.0,NaN,4.0,22.0,USD United States dollar,7.0,3.0,14.0,NaN,3.0,Yes,1.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,NaN,6.0,Favorable,NaN,4.0,Yes,Work,10.0,NaN,21.0,NaN,NaN,NaN,2.0,4.0,4.0,NaN,60000.0,6.0,6.0,Yes,NaN,"Yes, I use AI tools weekly",35-44 years old,NaN,"No, not really",5.0,NaN,7.0,Engineering manager,15.0,"Yes, I learned how to use AI-enabled tools for...","critical thinking, the skill to define the tas...",14.0,9.0,"Independent contractor, freelancer, or self-em...","No, and I don't plan to",2.0,NaN,NaN,NaN,Technical documentation (is generated for/by t...,When I don’t trust AI’s answers,NaN,NaN,Software Development,Ukraine,NaN,I am a developer by profession
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I code primarily as a hobby
49187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Caring for dependents (children, elderly, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some college/university study without earning ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45-54 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,Employed,NaN,NaN,NaN,Online Courses or Certification (includes all ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am a developer by profession
49188,7.0,9.0,NaN,NaN,NaN,I have somewhat considered changing my career ...,NaN,NaN,NaN,None of the above,NaN,7.0,Not at all or minimally,9.0,2.0,Neither trust nor distrust,10.0,NaN,2.0,NaN,NaN,12.0,NaN,1.0,No,5.0,5.0,NaN,"Yes, I endorsed a tool that was open-source an...",NaN,NaN,1.0,NaN,NaN,NaN,NaN,3.0,"Yes, I am not new to coding but am learning ne...",13.0,People manager,NaN,"Yes, partially.",NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,"AI solutions that are almost right, but not qu...","Good, but not great at handling complex tasks",NaN,9.0,NaN,4.0,11.0,NaN,NaN,7.0,NaN,6.0,9.0,5.0,NaN,4.0,31.0,EUR European Euro,NaN,35.0,8.0,NaN,14.0,NaN,8.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Hybrid (some in-person, leans heavy to flexibi...",NaN,NaN,Favorable,NaN,NaN,NaN,Personal Project,NaN,NaN,17.0,NaN,NaN,NaN,NaN,6.0,25.0,NaN,80000.0,1.0,4.0,NaN,NaN,"Yes, I use AI tools monthly or infrequently",35-44 years old,NaN,NaN,10.0,NaN,8.0,"Architect, software or solutions",15.0,"Yes, I learned how to use AI-enabled tools for...",NaN,10.0,3.0,Employed,"No, I use AI exclusively in copilot/autocomple...",6.0,"10,000 or more employees",Online Courses or Certification (includes all ...,NaN,AI CodeGen tools or AI-enabled apps;Videos (no...,NaN,NaN,NaN,Banking/Financial Services,Italy,NaN,I am a developer by profession
49189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,Videos (not associated with specific online co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am a developer by profession
49190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Attending school (full-time),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some college/university study without earning ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24 years old,NaN,NaN,NaN,NaN,NaN,Student,NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,Student,NaN,NaN,NaN,Online Courses or Certification (includes all ...,NaN,AI CodeGen tools or AI-enabled apps,NaN,NaN,NaN,NaN,NaN,NaN,"I am not primarily a developer, but I write co..."

In [43]:
df_common.dropna().shape

#немає жодного респондента, який би дав відповіді на ВСІ запитання

(0, 126)

Завдання 3. Статистичний аналіз досвіду респондентів

In [63]:
df_work_exp = df_res['WorkExp'].dropna()

avg = df_work_exp.mean().round(2)
med = df_work_exp.median()
mod = df_work_exp.mode()[0]

print ('Міри центральної тенденції:' )
series = pd.Series([avg, med, mod], index=['Mean', 'Median', 'Mode'])
print(series)

#Співвідношення результатів:
#якщо Середнє (Mean) > Медіани (Median), то це означає, що серед даних є невелика група людей із високими показниками
#тобто, є певна кількість респондентів з дуже великим досвідом роботи, вони "тягнуть" середнє значення вгору
#надійнішим показником для аналітики в даному випадку буде значення Середнього (Median)

Міри центральної тенденції:
Mean      13.37
Median    10.00
Mode      10.00
dtype: float64

Завдання 4. Аналіз віддаленої роботи

In [91]:
df_remote = df_res['RemoteWork'].dropna()

remote_work_numb = df_remote.value_counts()
remote_work_numb

#віддалено працює 10931 респондент

RemoteWork
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [92]:
remote_work_perc = df_remote.value_counts(normalize=True) * 100
remote_work_perc.round(2)

#отже, віддалено працює майже третина (32.36%) всіх опитаних

RemoteWork
Remote                                                                          32.36
Hybrid (some remote, leans heavy to in-person)                                  19.93
In-person                                                                       17.89
Hybrid (some in-person, leans heavy to flexibility)                             17.26
Your choice (very flexible, you can come in when you want or just as needed)    12.56
Name: proportion, dtype: float64

Завдання 5. Визначення популярності Python

In [105]:
df_res['worked_with_python'] = df_res['LanguageHaveWorkedWith'].str.contains(r'\bPython\b', case=False, na=False)
print(df_res['worked_with_python'].value_counts())

#знаходимо кількість python-розробників за кількістю булевих значень True

worked_with_python
False    30781
True     18410
Name: count, dtype: int64

In [112]:
total_resp = len(df_res)
python_resp = df_res['worked_with_python'].sum()

perc_python = python_resp / total_resp * 100
print (f'Відсоток респондентів, які програмують на Python: {perc_python.round(2)} %')

#на Python програмують лише 37.43% опитаних респондентів або 18410 осіб

Відсоток респондентів, які програмують на Python: 37.43 %

Завдання 6. Аналіз шляхів навчання програмуванню

In [116]:
df_res['learned_with_online_courses'] = df_res['LearnCode'].str.contains(r'\bOnline Courses\b', case=False, na=False)
print(df_res['learned_with_online_courses'].value_counts())

#знаходимо кількість розробників, котрі закінчили онлайн курси, за кількістю булевих значень True

learned_with_online_courses
False    38218
True     10973
Name: count, dtype: int64

In [115]:
print (f'Кількість респондентів, які закінчили онлайн курси: {df_res['learned_with_online_courses'].sum()}')

Кількість респондентів, які закінчили онлайн курси: 10973

Завдання 7. Географічний аналіз компенсації Python-розробників

In [125]:
df_python = df_res[df_res['worked_with_python'] & df_res['ConvertedCompYearly'].notna()]
df_python

#залишаємо python розробників, які вказали рівень зарплати

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat,worked_with_python,learned_with_online_courses
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0,True,False
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Blogs or p...,30.0,"Architect, software or solutions",Less than 20 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Personal Project,12.0,2.0,1.0,10.0,4.0,5.0,8.0,6.0,7.0,14.0,NaN,14.0,3.0,4.0,9.0,1.0,5.0,2.0,11.0,12.0,15.0,NaN,Software Development,7.0,9.0,11.0,10.0,14.0,12.0,4.0,2.0,5.0,13.0,6.0,3.0,1.0,15.0,8.0,NaN,Yes,I have strongly considered changing my career ...,10.0,10.0,Ukraine,USD United States dollar,72000.0,Yes,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,Assembly;Bash/Shell (all shells);HTML/CSS;Java...,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,NaN,NaN,Yes,MongoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,PostgreSQL;SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Google Cl...,APT;Cargo;Docker;Homebrew;Pip,APT;Docker;Homebrew;Pip,NaN,NaN,Yes,Angular;Django,Django,Django,NaN,NaN,Yes,PyCharm;Visual Studio Code;WebStorm,Claude Code;PyCharm;Visual Studio Code,PyCharm;Visual Studio Code,NaN,NaN,Amazon Bedrock,Odoo;Large Language Model;RAG,NaN,NaN,NaN,MacOS;iOS;iPadOS,MacOS;Ubuntu;Linux (non-WSL),GitHub;Jira,GitHub;GitLab;Jira;Wikis,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;Reddit;GitHub (p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),Anthropic: Claude Sonnet;openAI GPT (chatbot m...,openAI GPT (chatbot models),NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,7.0,NaN,10.0,1.0,6.0,5.0,4.0,2.0,11.0,15.0,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Writing code;Documenting code,NaN,Project planning;Debugging or fixing code;Depl...,Learning about a codebase;Testing code;Committ...,Search for answers;Learning new concepts or te...,"AI solutions that are almost right, but not qu...",Yes,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have concerns about the security and privacy...,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0,True,False
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,15.0,Data engineer,"5,000 to 9,999 employees",Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Personal Project,5.0,7.0,13.0,4.0,9.0,8.0,12.0,2.0,11.0,14.0,NaN,11.0,13.0,10.0,1.0,5.0,9.0,7.0,8.0,2.0,15.0,NaN,Banking/Financial Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have transitioned into a new career and/or i...,NaN,NaN,Ukraine,USD United States dollar,70000.0,NaN,Java;Python;Scala,Scala,Scala,NaN,NaN,NaN,Cassandra;Databricks SQL;DuckDB;Dynamodb;Maria...,Dynamodb;MySQL;PostgreSQL,Dynamodb;MySQL;PostgreSQL,NaN,NaN,NaN,Amazon Web Services (AWS);Datadog;Docker;Micro...,Amazon Web Services (AWS);Datadog;Microsoft Azure,Amazon Web Services (AWS);Datadog;Microsoft Azure,NaN,NaN,NaN,FastAPI;Spring Boot,NaN,NaN,NaN,NaN,NaN,IntelliJ IDEA;Notepad++;PyCharm;Visual Studio ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Neither good or bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Data and analytics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0,True,True
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,11.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,9.0,10.0,1.0,11.0,4.0,2.0,5.0,14.0,NaN,14.0,2.0,8.0,12.0,4.0,1.0,13.0,10.0,3.0,15.0,NaN,Fintech,3.0,2.0,4.0,6.0,9.0,10.0,5.0,11.0,8.0,12.0,1.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,10.0,United States of America,USD United States dollar,87500.0,Yes,C#;C++;JavaScript;Python;Visual Basic (.Net),C#;Python,C#;Python,NaN,NaN,Yes,Microsoft SQL Server,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Microsoft Azure,Microsoft Azure,NaN,NaN,Yes,ASP.NET;ASP.NET Core;jQuery,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,NaN,NaN,Yes,Notepad++;PyCharm;Visual Studio;Visual Studio ...,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Windows,Azure Devops;GitHub;Obsidian;Stack Overflow fo...,Azure Devops;GitHub;Obsidian,Azure Devops;GitHub;Obsidian,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Stack Overflow;Stack Exchange;Discord;Reddit;H...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,"Lists of recommendations (tools, frameworks, t...",4.0,NaN,8.0,1.0,12.0,11.0,10.0,2.0,9.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Unfavorable,Somewhat distrust,Bad at handling complex tasks,Writing code,Learning about a codebase;Project planning;Doc...,Debugging or fixing code;Creating or maintaini...,Predictive analytics,NaN,"AI solutions that are almost right, but not qu...","No. I find it to be useless, unless I'm starti...","No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0,True,False
27,28,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",24.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,36.0,"Developer, full-stack","1,000 to 4,999 employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)",No,Work,12.0,1.0,9.0,7.0,4.0,13.0,5.0,6.0,3.0,14.0,NaN,14.0,7.0,12.0,10.0,6.0,3.0,2.0,8.0,1.0,15.0,NaN,Banking/Financial Services,1.0,4.0,8.0,12.0,6.0,10.0,5.0,9.0,11.0,13.0,3.0,7.0,2.0,15.0,14.0,NaN,I'm not sure,I have somewhat considered changing my career ...,10.0,4.0,Sweden,SEK\tSwedish krona,2000000.0,Yes,C#;Java;Python;SQL,C#;Java;SQL,C#;Java;SQL,NaN,NaN,Yes,Microsoft SQL Server;Oracle;PostgreSQL,Microsoft SQL Server;Oracle;PostgreSQL,Microsoft SQL Server;Oracle;PostgreSQL,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Blazor,Blazor,Blazor,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Ubuntu;Android;Linux (non-WSL),Windows;Linux (non-WSL),Jira,Jira;Trello,Jira,NaN,NaN,Stack Overflow;Stack Exchange;Reddit;Medium,Stack Overflow;Stack Exchange;Reddit,Stack Overflow;Stack Exchange;Reddit,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Daily or almost daily,Between 10 and 15 years,A few times per month or weekly,NaN,4.0,NaN,14.0,12.0,3.0,1.0,5.0,9.0,7.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,NaN,Learning about a codebase;Project planning;Doc...,Writing code,NaN,NaN,I don’t use AI tools regularly,No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,I am concerned about the accuracy of the infor...,I have concerns about the security and privacy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,209643.0,9.0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49028,49029,"I am not primarily a developer, but I write co...",25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,5.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,8.0,Cybersecurity or InfoSec professional,"1,000 to 4,999 employees",Individual contributor,Remote,"Yes, I endorsed a tool that was ultimately not...",Work,10.0,5.0,4.0,8.0,1.0,3.0,9.0,7.0,2.0,6.0,Integration with existing tooling,10.0,8.0,6.0,4.0,1.0,2.0,5.0,3.0,7.0,9.0,NaN,Banking/Financial Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have somewhat considered changing my career ...,NaN,NaN,United States of America,USD United States dollar,77000.0,Yes,Bash/Shell (all shells);C#;Java;Python,Bash/Shell (all shells);C#;Java;Kotlin;Python,Bash/Shell (all shells);C#;Java;Python,Haskell,Haskell,Yes,Microsoft SQL Server,NaN,NaN,NaN,NaN,Yes,Microsoft Azure,Microsoft Azure,Microsoft Azure,Oracle,NaN,Yes,ASP.NET Core;Node.js,ASP.NET Core,ASP.NET Core,NaN,NaN,Yes,Visual Studio Code,Visual Studio Code;VSCodium,Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linux (non-WSL),Windows,Azure Devops;GitHub;GitLab,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Reddit;GitHub (p...,Stack Overflow;Stack Exchange,Stack Overflow;Stack Exchange,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77000.0,NaN,True,False
49088,49089,I work with developers or my work supports dev...,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,15.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Blogs or p...,10.0,Engineering manager,100 to 499 employees,People manager,Remote,"Yes, I influenced the purchase of a tool that ...",Work,5.0,4.0,3.0,7.0,1.0,9.0,8.0,6.0,2.0,10.0,NaN,6.0,4.0,9.0,5.0,3.0,2.0,7.0,1.0,8.0,10.0,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have somewhat considered changing my career ...,20.0,NaN,United States of America,USD United States dollar,280000.0,Yes,Python;SQL,Python;SQL,Python;SQL,LLM Prompts,LLM Prompts,Yes,Databricks SQL;Snowflake,Databricks SQL;Snowflake,Databricks SQL;Snowflake,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Cursor;Notepad++,NaN,NaN,NaN,NaN,Large Language Model;Amazon Bedrock;RAG;Google...,Large Language Model;RAG;Google Gemini,Large Language Model;RAG;Google Gemini,NaN,NaN,Windows;Android,Windows,GitHub;Jira;Stack Overflow for Teams,GitHub;Jira,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;Hacker News,Stack Overflow;Stack Exchange;Hacker News,Stack Overflow;Stack Exchange;Hacker News,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,280000.0,NaN,True,False

In [166]:
df_python_country = df_python.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median'])
df_python_country = df_python_country.rename(columns={
    'mean': 'Average Salary',
    'median': 'Median Salary'
}).round(2)
df_python_country

#групуємо відфільтровані дані по країнах
#знаходимо середнє та медіану
#виставляємо результат у вигляді таблиці

                                      Average Salary  Median Salary
Country
Afghanistan                                 22328.67         1000.0
Albania                                     59018.25        58889.5
Algeria                                     20187.29         7088.0
Andorra                                    226103.50       226103.5
Antigua and Barbuda                             1.00            1.0
...                                              ...            ...
Venezuela, Bolivarian Republic of...         9908.65         3000.0
Viet Nam                                   218837.17         8254.0
Yemen                                       32929.50        23672.0
Zambia                                       5424.25         3206.0
Zimbabwe                                    34000.00        25500.0

[153 rows x 2 columns]

Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [139]:
df_salary = df_res[['ResponseId', 'EdLevel', 'ConvertedCompYearly']].dropna()
df_salary

#виокремлюємо необхідні стовпчики для проведення аналізу рівня освіти респондентів

,ResponseId,EdLevel,ConvertedCompYearly
0,1,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",61256.0
1,2,"Associate degree (A.A., A.S., etc.)",104413.0
2,3,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",53061.0
3,4,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",36197.0
4,5,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",60000.0
...,...,...,...
49098,49099,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",2729.0
49105,49106,Some college/university study without earning ...,719.0
49106,49107,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",69008.0
49121,49122,"Associate degree (A.A., A.S., etc.)",58007.0
49122,49123,Some college/university study without earning ...,46406.0

In [142]:
df_salary_top_5 = df_salary.sort_values(by='ConvertedCompYearly', ascending=False).reset_index(drop=True).head(5)
df_salary_top_5

#визначаємо топ-5 розробників по рівню зарплати

,ResponseId,EdLevel,ConvertedCompYearly
0,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
1,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
2,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
3,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
4,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0

*Завдання 9. Аналіз популярності Python по віковим категоріям

In [143]:
df_res['Age'].unique()

#перевіряємо вікові категорії респондентів

array(['25-34 years old', '35-44 years old', '45-54 years old',
       '18-24 years old', '65 years or older', '55-64 years old',
       'Prefer not to say'], dtype=object)

In [167]:
age_df = df_res.groupby('Age')['worked_with_python'].mean() * 100
age_python = age_df.round(2).reset_index()
age_python.columns = ['Вікова категорія', 'Відсоток Python-розробників, %']
age_python

#групуємо розробників за віком та визначаємо % тих, які програмують на python
#в середньому кожні 30-40% кожної вікової категорії розробників програмують на python

    Вікова категорія  Відсоток Python-розробників, %
0    18-24 years old                           39.93
1    25-34 years old                           36.82
2    35-44 years old                           36.62
3    45-54 years old                           38.45
4    55-64 years old                           37.17
5  65 years or older                           31.32
6  Prefer not to say                           30.95

*Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [151]:
salary_higher75 = df_res['ConvertedCompYearly'].quantile(0.75)
salary_higher75

#визнаємо 75 перцентиль за компенсацією, результат - 120596,0

np.float64(120596.0)

In [154]:
high_remote_workers = df_res[(df_res['ConvertedCompYearly'] >= salary_higher75) & (df_res['RemoteWork'] == 'Remote')]
high_remote_workers

#виокремлюємо респондентів, котрі працюють віддалено та мають зарплату більше ніж в інших 75% опитаних

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat,worked_with_python,learned_with_online_courses
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,15.0,"Developer, mobile",500 to 999 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,9.0,3.0,4.0,8.0,11.0,7.0,5.0,1.0,10.0,14.0,NaN,12.0,4.0,5.0,9.0,14.0,7.0,11.0,6.0,2.0,15.0,NaN,Software Development,7.0,6.0,9.0,10.0,11.0,12.0,13.0,5.0,14.0,8.0,1.0,3.0,4.0,15.0,2.0,NaN,No,I have neither consider or transitioned into a...,6.0,6.0,United States of America,USD United States dollar,205000.0,Yes,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,NaN,NaN,NaN,NaN,Yes,MySQL;PostgreSQL;SQLite;Supabase,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,NaN,NaN,NaN,Yes,Next.js;Node.js;React,NaN,NaN,"Remix, Capacitor, Ionic",NaN,Yes,Android Studio;Claude Code;Cursor;IntelliJ IDE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;Linux (non-WSL),Windows;MacOS;Android;Linux (non-WSL),GitHub;GitLab;Google Workspace;Jira;Notion;Tre...,NaN,NaN,NaN,NaN,Discord;Reddit;Hacker News;GitHub (public proj...,NaN,NaN,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Between 10 and 15 years,"Infrequently, less than once per year",Chat (bot/AI),10.0,NaN,9.0,6.0,1.0,5.0,13.0,12.0,8.0,15.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat distrust,Very poor at handling complex tasks,Writing code;Learning new concepts or technolo...,Project planning;Deployment and monitoring;Pre...,Learning about a codebase;Testing code,Committing and reviewing code;Creating or main...,Documenting code;Debugging or fixing code;Sear...,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0,False,False
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,23.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,6.0,11.0,10.0,9.0,8.0,2.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fintech,2.0,3.0,4.0,11.0,12.0,5.0,6.0,10.0,7.0,8.0,9.0,13.0,14.0,15.0,1.0,NaN,No,I have neither consider or transitioned into a...,5.0,8.0,United States of America,USD United States dollar,250000.0,Yes,Elixir;HTML/CSS;JavaScript;SQL;TypeScript,Elixir;HTML/CSS;OCaml;Gleam,Elixir;HTML/CSS,NaN,NaN,Yes,BigQuery;Elasticsearch;PostgreSQL;SQLite,SQLite,SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Datadog;D...,Cloudflare;Homebrew;Make,Cloudflare;Homebrew;Make,hex,hex,Yes,Node.js;Phoenix;React,Phoenix,Phoenix,NaN,NaN,Yes,NaN,NaN,NaN,emacs,emacs,Tailwind CSS 4;Large Language Model,Tailwind CSS 4,Tailwind CSS 4,NaN,NaN,MacOS,MacOS,Airtable;Confluence;GitHub;Google Workspace;Ji...,NaN,NaN,NaN,NaN,Reddit;Dev.to;Hacker News;GitHub (public proje...,"GitHub (public projects, not private repos);Sl...","GitHub (public projects, not private repos);Sl...",NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,I don’t use AI tools regularly,no,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0,False,False
41,42,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Transitioning to retirement (gradually reducin...,25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training;Online Course...,25.0,"Developer, front-end",Less than 20 employees,Individual contributor,Remote,No,Personal Project,4.0,2.0,12.0,7.0,6.0,11.0,8.0,5.0,1.0,14.0,NaN,12.0,1.0,9.0,4.0,5.0,3.0,8.0,7.0,2.0,15.0,NaN,Software Development,5.0,2.0,6.0,11.0,10.0,8.0,7.0,9.0,12.0,13.0,1.0,14.0,3.0,15.0,4.0,NaN,Yes,I have somewhat considered changing my career ...,3.0,2.0,United States of America,USD United States dollar,270000.0,Yes,HTML/CSS;JavaScript;Python;TypeScript,HTML/CSS;JavaScript;Python;TypeScript,HTML/CSS;JavaScript;Python;TypeScript,NaN,NaN,Yes,PostgreSQL,PostgreSQL,PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Datadog;Homebrew;npm;Vercel;Vite,Datadog;Homebrew;npm;Vercel;Vite,NaN,NaN,Yes,Next.js;Node.js;React;Svelte,Svelte,Svelte,NaN,NaN,Yes,Cursor,Cursor,Cursor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS;iOS,MacOS;Linux (non-WSL),GitHub;Linear;Notion,GitHub;Linear;Notion,GitHub;Linear;Notion,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,Anthropic: Claude Sonnet,Anthropic: Claude Sonnet,Anthropic: Claude Sonnet,NaN,NaN,Yes,A few times per week,"More than 15 years, or since Stack Overflow st...",A few times per month or weekly,Chat (people);Job board,10.0,NaN,8.0,9.0,1.0,4.0,14.0,11.0,5.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Favorable,Somewhat distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Project planning;Committing and reviewing code...,Deployment and monitoring;Creating or maintain...,Testing code,Generating content or synthetic data,"AI solutions that are almost right, but not qu...",No. Vibe coding is fine for demos but not prof...,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,I am concerned about the accuracy of the infor...,NaN,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Requirements gathering, big fixing",270000.0,3.0,True,True
42,43,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc....",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,35.0,"Developer, mobile","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Personal Project,8.0,3.0,2.0,6.0,7.0,1.0,5.0,4.0,9.0,14.0,NaN,8.0,1.0,6.0,2.0,4.0,9.0,7.0,13.0,14.0,15.0,NaN,Software Development,3.0,4.0,9.0,12.0,13.0,14.0,6.0,2.0,7.0,8.0,1.0,10.0,5.0,15.0,11.0,NaN,No,I have neither consider or transitioned into a...,10.0,10.0,United States of America,USD United States dollar,250000.0,Yes,Bash/Shell (all shells);C;C#;C++;HTML/CSS;Java...,Assembly;Go;Ruby;Rust,NaN,NaN,NaN,NaN,Microsoft SQL Server;MySQL;Oracle;SQLite,Cosmos DB;DuckDB;Dynamodb;IBM DB2;InfluxDB;Mon...,NaN,NaN,NaN,NaN,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,Yes,AngularJS;ASP.NET;ASP.NET Core;Django;jQuery;N...,Ruby on Rails;Spring Boot,Ruby on Rails,NaN,NaN,Yes,Android Studio;Claude Code;Eclipse;IntelliJ ID...,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Google Gemini,NaN,NaN,NaN,NaN,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Azure Devops;Coda;Doxygen;GitHub;GitLab;Google...,Airtable;Obsidian;Stack Overflow for Teams;Trello,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Company-sponsored forums,Company-sponsored forums,NaN,NaN,Yes,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Alibaba Cloud Qwen models;Amazon Titan models;...,Anthropic: Claude Sonnet,NaN,NaN,Yes,Daily or almost daily,Between 10 and 15 years,A few times per month or weekly,Message Boards;Long-form articles,9.0,NaN,6.0,2.0,4.0,1.0,8.0,7.0,11.0,15.0,NaN,"Yes, definitely",Less than half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Very well at handling complex tasks,Documenting code;Generating content or synthet...,NaN,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Debuggi...,Other (write in):,Yes. Use it daily.,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering,Language processing;Agent/multi-agent orchestr...,AI agents have increased my productivity.;AI a...,AI agents have improved collaboration within m...,NaN,AI agents have helped me automate repetitive t...,NaN,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis;ChromaDB,NaN,Llama Index;Ollama;OpenRouter,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I want to fully understand something;When...,Multiplatform Platform code conversion. Langua...,250000.0,8.0,True,True
48,49,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,21.0,"Senior executive (C-suite, VP, etc.)",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,6.0,12.0,1.0,10.0,9.0,4.0,2.0,14.0,NaN,14.0,6.0,11.0,10.0,1.0,2.0,5.0,9.0,3.0,15.0,NaN,Fintech,5.0,6.0,7.0,13.0,12.0,8.0,11.0,9.0,10.0,14.0,1.0,3.0,2.0,15.0,4.0,NaN,I'm not sure,I have somewhat considered changing my career ...,10.0,5.0,United Kingdom of Great Britain and Northern I...,GBP Pound sterling,105000.0,Yes,C#;Elixir;HTML/CSS;JavaScript;SQL;TypeScript,C#;Elixir;HTML/CSS;SQL,C#;Elixir;HTML/CSS;SQL,Haskell,NaN,Yes,Cosmos DB;Elasticsearch;Microsoft SQL Server;P...,Cosmos DB;Microsoft SQL Server;PostgreSQL,Cosmos DB;Microsoft SQL Server;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Docker;Go...,Amazon Web Services (AWS);Cloudflare;Docker;Mi...,Amazon Web Services (AWS);Cloudflare;Docker;Mi...,NaN,NaN,Yes,ASP.NET Core;Next.js;Phoenix,ASP.NET Core;Blazor;Phoenix,ASP.NET Core;Phoenix,NaN,Ash,Yes,Aider;Claude Code;Cursor;Jupyter Notebook/Jupy...,Jupyter Notebook/JupyterLab;Neovim;Rider;Visua...,Jupyter Notebook/JupyterLab;Neovim;Rider;Visua...,NaN,NaN,Tailwind CSS 4;Large Language Model;Shadcn/ui,Tailwind CSS 4;Microsoft Fabric;Shadcn/ui,Tailwind CSS 4;Shadcn/ui,NaN,NaN,Windows;MacOS;iOS,MacOS;Ubuntu;Linux (non-WSL),Azure Devops;Confluence;GitHub;Google Workspac...,GitHub;Google Workspace;Lucid (includes Lucidc...,GitHub;Google Workspace;Notion,Whimsical,Whimsical,Stack Overflow;Reddit;Hacker News;GitHub (publ...,Stack Overflow;Discord;Reddit;Hacker News;GitH...,Stack Overflow;Reddit;Hacker News;GitHub (publ...,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,Anthropic: Claude Sonnet;Gemini (Pro Reasoning...,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",Long-form articles;Coding challenges;Lists of ...,9.0,NaN,10.0,6.0,1.0,2.0,8.0,11.0,14.0,15.0,NaN,"Yes, somewhat",Less than half of the time,"Yes, I use AI tools monthly or infrequently",Unfavorable,Highly distrust,Very poor at handling complex tasks,Writing code;Debugging or fixing code;Learning...,Project planning;Documenting code;Deployment a...,Learning about a codebase;Testing code;Committ...,Generating content or synthetic data,NaN,"AI solutions that are almost right, but not qu...",No,"No, but I plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,My company's IT and/or InfoSec teams have stri...,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"Problem solving and reasoning, unless we get f...",142949.0,7.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48913,48914,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,20.0,"Developer, mobile",Less than 20 employees,Individual contributor,Remote,No,Personal Project,8.0,2.0,3.0,9.0,5.0,6.0,7.0,4.0,1.0,10.0,NaN,9.0,6.0,2.0,7.0,1.0,4.0,3.0,5.0,8.0,10.0,NaN,Software Development,9.0,3.0,12.0,2.0,5.0,14.0,10.0,4.0,8.0,13.0,1.0,11.0,6.0,15.0,7.0,NaN,I'm not sure,I have neither consider or transitioned into a...,10.0,10.0,United Kingdom of Great Britain and Northern I...,GBP Pound sterling,95000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,"More than 15 years, or since Stack Overflow st...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129334.0,9.0,False,False

In [163]:
df_industry = high_remote_workers['Industry'].value_counts()
df_industry_remote = df_industry.reset_index()
df_industry_remote.columns = ['Industry', 'Count of remote workers']
df_industry_remote

#наводимо таблицю, згруповану по індустріях та кількістю респондентів (заплата >75% ніж в інших), котрі працюють віддалено

                                      Industry  Count of remote workers
0                         Software Development                     1186
1                                      Fintech                      190
2                                   Healthcare                      188
3                                       Other:                      176
4   Internet, Telecomm or Information Services                      138
5                   Banking/Financial Services                       88
6                                   Government                       78
7                 Media & Advertising Services                       75
8                 Retail and Consumer Services                       65
9              Transportation, or Supply Chain                       63
10        Computer Systems Design and Services                       59
11                                   Insurance                       46
12                                      Energy                       45
13                               Manufacturing                       33
14                            Higher Education                       30